//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Starship.Language.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnglishResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnglishResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Starship.Language.Resources.EnglishResources", typeof(EnglishResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bl
        ///cl
        ///fl
        ///gl
        ///pl
        ///sl
        ///br
        ///cr
        ///dr
        ///fr
        ///gr
        ///pr
        ///tr
        ///sc
        ///sk
        ///sm
        ///sn
        ///sp
        ///st
        ///sw
        ///tw
        ///br
        ///cr
        ///dr
        ///fr
        ///gr
        ///pr
        ///tr
        ///sc
        ///sk
        ///sm
        ///sn
        ///sp
        ///st
        ///sw
        ///scr
        ///squ
        ///str
        ///spr
        ///spl
        ///bl
        ///cl
        ///fl
        ///gl
        ///pl
        ///sl
        ///st
        ///sp
        ///sm
        ///sn
        ///sc
        ///sk
        ///sw
        ///squ
        ///pr
        ///tr
        ///br
        ///cr
        ///dr
        ///fr
        ///gr
        ///scr
        ///spr
        ///str
        ///tw
        ///dw
        ///cl
        ///fl
        ///gl
        ///pl
        ///sl
        ///bl
        ///spl.
        /// </summary>
        internal static string blends {
            get {
                return ResourceManager.GetString("blends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9081174698 a
        ///30523331 aa
        ///10243983 aaa
        ///18972 aaberg
        ///751750 aachen
        ///13182 aachener
        ///339838 aah
        ///33435 aaker
        ///3330218 aaliyah
        ///31269 aamodt
        ///21950 aardema
        ///629356 aardvark
        ///34369 aardvarks
        ///71592 aargh
        ///11698784 aaron
        ///238761 aarons
        ///91216 aaronson
        ///63273 aarti
        ///37765 aase
        ///19449 aasen
        ///24218038 ab
        ///2724411 aba
        ///514159 ababa
        ///94146 abacha
        ///272920 aback
        ///225849 abaco
        ///1017068 abacus
        ///193291 abad
        ///101263 abadi
        ///27501 abadie
        ///32093 abair
        ///518562 abalone
        ///17658 abalos
        ///2747961 abandon
        ///6371760 abandoned
        ///77890 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ngrams_filtered {
            get {
                return ResourceManager.GetString("ngrams_filtered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9081174698 a
        ///30523331 aa
        ///10243983 aaa
        ///1595769 aaaa
        ///52821 aaaah
        ///33992 aaaai
        ///19170 aaaargh
        ///28795 aaab
        ///22135 aaabooksearch
        ///31631 aaac
        ///60117 aaace
        ///161080 aaacn
        ///31136 aaacom
        ///56263 aaae
        ///14111 aaag
        ///149544 aaah
        ///20882 aaahh
        ///21124 aaahhh
        ///256233 aaai
        ///25310 aaal
        ///17551 aaalac
        ///23967 aaand
        ///12802 aaaol
        ///18876 aaap
        ///45209 aaargh
        ///415131 aaas
        ///20522 aaasc
        ///17533 aaat
        ///333019 aab
        ///44390 aaba
        ///94557 aabb
        ///54128 aabbccdd
        ///34103 aabc
        ///14985 aabd
        ///14532 aabenraa
        ///18972 aaberg
        ///22187 aabt
        ///2501919 aac
        ///60754  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ngrams1 {
            get {
                return ResourceManager.GetString("ngrams1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 275 a a
        ///31 a aaa
        ///29 a all
        ///45 a an
        ///192 a and
        ///39 a another
        ///25 a at
        ///82 a b
        ///168 a b.a
        ///64 a b.f.a
        ///84 a b.s
        ///45 a b+
        ///26 a b-17
        ///31 a b-2
        ///54 a b-52
        ///66 a ba
        ///41 a babble
        ///28 a babbling
        ///159 a babe
        ///83 a baboon
        ///9744 a baby
        ///31 a baby-faced
        ///237 a babysitter
        ///122 a baby-sitter
        ///23 a babysitting
        ///95 a baccalaureate
        ///71 a bach
        ///1342 a bachelor
        ///27 a bachelorette
        ///53 a bachelors
        ///1924 a back
        ///38 a back-and-forth
        ///53 a backboard
        ///72 a backbone
        ///93 a backcountry
        ///60 a backdoor
        ///24 a back-door
        ///728 a backdrop [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ngrams2 {
            get {
                return ResourceManager.GetString("ngrams2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 a b.a degree
        ///56 a b.a in
        ///41 a b.s in
        ///33 a ba in
        ///35 a babble of
        ///33 a babe in
        ///316 a baby and
        ///25 a baby as
        ///73 a baby at
        ///32 a baby before
        ///53 a baby bird
        ///57 a baby boomer
        ///34 a baby born
        ///146 a baby boy
        ///36 a baby brother
        ///29 a baby by
        ///34 a baby can
        ///45 a baby carriage
        ///45 a baby crying
        ///39 a baby doll
        ///47 a baby for
        ///41 a baby from
        ///224 a baby girl
        ///35 a baby grand
        ///30 a baby has
        ///350 a baby in
        ///27 a baby into
        ///216 a baby is
        ///29 a baby now
        ///38 a baby of
        ///142 a baby on
        ///78 a baby or
        ///33 a baby out [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ngrams3 {
            get {
                return ResourceManager.GetString("ngrams3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17 a b.a degree from
        ///20 a b.a degree in
        ///15 a b.s degree in
        ///18 a babe in the
        ///37 a baby and a
        ///17 a baby and i
        ///14 a baby and she
        ///13 a baby and then
        ///13 a baby and you
        ///17 a baby at the
        ///17 a baby grand piano
        ///68 a baby in a
        ///44 a baby in her
        ///76 a baby in the
        ///13 a baby in your
        ///13 a baby into the
        ///19 a baby is a
        ///37 a baby is born
        ///13 a baby of her
        ///32 a baby on her
        ///58 a baby on the
        ///19 a baby or a
        ///26 a baby out of
        ///15 a baby to sleep
        ///16 a baby when you
        ///16 a baby who is
        ///13 a baby who was
        ///42 a bab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ngrams4 {
            get {
                return ResourceManager.GetString("ngrams4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16 a babe in the woods
        ///6 a baby at her breast
        ///9 a baby brother or sister
        ///6 a baby crying in the
        ///6 a baby girl was born
        ///8 a baby in a stroller
        ///28 a baby in her arms
        ///6 a baby in his arms
        ///11 a baby in the house
        ///12 a baby into the world
        ///13 a baby of her own
        ///12 a baby on her hip
        ///42 a baby on the way
        ///16 a baby out of wedlock
        ///25 a bachelor of arts degree
        ///9 a bachelor of arts in
        ///14 a bachelor of fine arts
        ///30 a bachelor of science degree
        ///10 a bachelor of science in
        ///7 a back corner of the
        ///8 a back [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ngrams5 {
            get {
                return ResourceManager.GetString("ngrams5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA  vowel       glottal         1
        ///AE	vowel       glottal         2   catch algae larvae vitae
        ///AH	vowel       glottal         3   casbah cheetah
        ///AO	vowel       glottal         6
        ///AW	vowel       glottal         7
        ///AY	vowel       glottal         8
        ///B	stop        bilabial        1
        ///CH	affricate   postalveolar    0
        ///D	stop        alveolar        1
        ///DH	fricative   interdental     0
        ///EH	vowel       glottal         2   fetch else enlist
        ///ER	vowel       glottal         9
        ///EY	vowel       glottal         4
        ///F	frica [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string phonemes {
            get {
                return ResourceManager.GetString("phonemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after 
        ///anti 
        ///back 
        ///be 
        ///by 
        ///down 
        ///fore 
        ///hind 
        ///mid 
        ///midi 
        ///mini 
        ///mis 
        ///off 
        ///on 
        ///out 
        ///over 
        ///pro 
        ///re 
        ///self 
        ///step 
        ///twi 
        ///un 
        ///under 
        ///up 
        ///with 
        ///Afro 
        ///ambi 
        ///amphi 
        ///an
        ///ana
        ///Anglo
        ///ante
        ///apo
        ///ap  
        ///arch 
        ///astro 
        ///auto 
        ///bi 
        ///bio 
        ///circum 
        ///cis 
        ///con
        ///co
        ///com
        ///col
        ///cor  
        ///contra
        ///contro  
        ///counter 
        ///cryo 
        ///crypto 
        ///de 
        ///demi 
        ///demo 
        ///deuter 
        ///di 
        ///dia 
        ///dis
        ///dif 
        ///du
        ///duo 
        ///eco 
        ///electro 
        ///en
        ///el
        ///em  
        ///epi
        ///ep  
        ///Euro 
        ///ex 
        ///extra 
        ///Franco 
        ///geo 
        ///gyro 
        ///hetero 
        ///hemi 
        ///homo 
        ///hydro 
        ///hyper  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string prefixes {
            get {
                return ResourceManager.GetString("prefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !exclamation-point eh k s k l ah m ey sh ah n p oy n t
        ///&quot;close-quote k l ow z k w ow t
        ///&quot;double-quote d ah b ah l k w ow t
        ///&quot;end-of-quote eh n d ah v k w ow t
        ///&quot;end-quote eh n d k w ow t
        ///&quot;in-quotes ih n k w ow t s
        ///&quot;quote k w ow t
        ///&quot;unquote ah n k w ow t
        ///#sharp-sign sh aa r p s ay n
        ///%percent p er s eh n t
        ///&amp;ampersand ae m p er s ae n d
        ///&apos;apostrophe ah p aa s t r ah f iy
        ///&apos;bout b aw t
        ///&apos;cause k ah z
        ///&apos;course k ao r s
        ///&apos;cuse k y uw z
        ///&apos;em ah m
        ///&apos;end-inner-quote eh n d ih n er k w ow t
        ///&apos;end-quote eh n d k  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pronounce {
            get {
                return ResourceManager.GetString("pronounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a cap-pel-la
        ///a for-ti-o-ri
        ///a go-go
        ///a pos-te-ri-o-ri
        ///a pri-o-ri
        ///a tem-po
        ///a-plen-ty
        ///Aal-borg
        ///Aal-to
        ///aard-vark
        ///aard-wolf
        ///Aar-au
        ///Aar-gau
        ///Aar-hus
        ///Aar-on
        ///Aar-on-it-ic
        ///Aa-chen
        ///Aa-le-sund
        ///aa-li-i
        ///Aa-ron
        ///Aa-ron&apos;s beard
        ///Aa-ron&apos;s rod
        ///Aa-ron&apos;s-beard
        ///Aa-ron-ic
        ///Aa-ron-ite
        ///Aa-ron-i-cal
        ///ab in-i-ti-o
        ///ab o-vo
        ///abb
        ///Abbe-vill-i-an
        ///Abbe-vil-e-an
        ///abbr
        ///abbrev
        ///Abd-al-Ka-dir
        ///Abd-al-Rah-man
        ///Abd-el-Ka-dir
        ///abl
        ///abp
        ///abr
        ///absinth
        ///ab-a
        ///ab-ac-ti-nal
        ///ab-amp
        ///ab-am-pere
        ///ab-ap-tis-ton
        ///ab-at-tis
        ///ab-at [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string syllables {
            get {
                return ResourceManager.GetString("syllables", resourceCulture);
            }
        }
    }
}
